# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'deploy'
  jobs:
  - deployment: 'DeployWeb'
    displayName: 'deploy Web App'
    
    pool:
      vmImage: 'Ubuntu-latest'
      
    environment: 'smarthotel-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
